### ISSUE TITLE
How to organize our directory structure?

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#1]
* Here are some references:
  * https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/
  * http://stackoverflow.com/questions/5178334/folder-structure-for-a-node-js-project
  * https://gist.github.com/lancejpollard/1398757
  * https://www.terlici.com/2014/08/25/best-practices-express-structure.html

**Comment by romandev** [comment]
What do you think? @daehyunjimmy, @gogag1, @JayChl, @nadongguri, @Wuseok, @hyungheo, @CoconutPerm

**Comment by romandev** [comment]
server/
client/
platform/
scripts/
tests/
run.cmd

**Comment by nadongguri** [comment]
honestly speaking, I have no experience of the latest web based programming so everything except me is new. I hope I will get used to this project at the end.

this is what I understand of that structure. Is it right?

server/ - core code and will be maintained by us.
client/ - code at the client side
platform/ - dependent code ? (docker or something? ) :-o.
scripts/ - dependent scripts for platforms. ( OSX, linux, Windwos and etc.)
tests/  - test suite, test automation code.
run.cmd - finally it runs node.js server on any platform using magic script in scripts folder.
