### ISSUE TITLE
[Hackathon] Implementation of Gallery feature UI

### ISSUE THREAD

**Issue by nadongguri** [romandev/absolute#102]
1. Choose UI framework
 2. Prototyping
 3. Design component or make it out for Hackathon

![new mockup 1](https://cloud.githubusercontent.com/assets/23691318/23411393/85ef33c4-fe15-11e6-9cc3-5cd4e1c35f49.png)
![new mockup 2](https://cloud.githubusercontent.com/assets/23691318/23411394/85f26404-fe15-11e6-8019-f9e8028d65ab.png)
![new mockup 3](https://cloud.githubusercontent.com/assets/23691318/23411395/85f31174-fe15-11e6-8a5e-a58fbb47eaf8.png)

**Comment by romandev** [comment]
This is great work!
Thank you for this work. Dongguri.

/cc @nadongguri, @coconutperm, @hyungheo
