### ISSUE TITLE
[Hackathon] Implementation of Camera API & Order page UI

### ISSUE THREAD

**Issue by cs-lee** [romandev/absolute#105]
User Interface Flow
![absoulte mockup 2](https://cloud.githubusercontent.com/assets/21388202/23411912/338c87ce-fe17-11e6-8845-8697ce88e7a5.png)

**Comment by romandev** [comment]
@cs-lee Thank you for this work.
This looks great!!

**Comment by cs-lee** [comment]
All feature released.
