### ISSUE TITLE
[Hackathon] Admin Page

### ISSUE THREAD

**Issue by JayChl** [romandev/absolute#106]
![admin1 password](https://cloud.githubusercontent.com/assets/23692016/23411816/e1aa3424-fe16-11e6-9c57-32c97f8eb228.png)
![admin2 orders](https://cloud.githubusercontent.com/assets/23692016/23411814/e1a5fc74-fe16-11e6-91f6-a7fc60e0c4b9.png)
![admin3 statistic](https://cloud.githubusercontent.com/assets/23692016/23411813/e1a4ea14-fe16-11e6-8e00-794a26b6bee1.png)
![admin3 manage](https://cloud.githubusercontent.com/assets/23692016/23411815/e1a7377e-fe16-11e6-9880-901051e96ece.png)
![admin4 settings](https://cloud.githubusercontent.com/assets/23692016/23411817/e1ab30c2-fe16-11e6-96cd-1facf67286d9.png)

Schedule 이나 timer 는 Orders 메뉴에서 임시로 일괄 Push / Schedule Push 를 넣으면 될것으로 생각함

**Comment by nadongguri** [comment]
Holy americano!

**Comment by romandev** [comment]
Looks very good to me.

This work is too large but you can do it ;)

Even if we implement related APIs fully, it's enough great :)
