### ISSUE TITLE
Should update node_modules when only package.json is changed.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#218]
Currently, node_modules are installed/updated whenever users run |absolute start| command.
But it's too inefficiency. Moreover, we don't need to install them again. (updating is enough).
So, we should make it update when only package.json is changed.

**Comment by nadongguri** [comment]
I will handle this.

**Comment by nadongguri** [comment]
This issue is solved by commit "update npm when package.json is changed (#232)" so I will close this issue.
