### ISSUE TITLE
We should use |import| instead of |require()|.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#231]
For example, in server.js

const express = require('express');
const path = require('path');
const bodyParser = require('body-parser');
....

We should change the above codes as follows:
import express from 'express';
import path from 'path';
import body_parser from 'body-parser';

**Comment by romandev** [comment]
@everyone Who can fix this issue?

**Comment by daehyunjimmy** [comment]
I will do this issue.

**Comment by nadongguri** [comment]
Close this issue. Solved by Replace require() method with import statement for ES6,7 support (#233)
