### ISSUE TITLE
We need LICENSE file.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#248]
Also, we need a discussion of what kind of licenses to use.

**Comment by nadongguri** [comment]
Even choosing license is required by everyone's agreement, I will check which license is close to absolute. :-)

**Comment by nadongguri** [comment]
I think the MIT would be good for our license because compared to
- Apache License 2.0 : State changes are required (ex: code changes should be documented.), shouldn't infringe the apache trademark.
- GPL v3 : disclose source code.

**Comment by nadongguri** [comment]
I will add this issue in milestone sprint #2 and split it to small tasks.
within Sprint #2, 
- review famous licenses and share it.
- vote.

**Comment by nadongguri** [comment]
#319 is applied. Close this issue. :-)
