### ISSUE TITLE
Investigate which database solution to use.

### ISSUE THREAD

**Issue by coconutperm** [romandev/absolute#28]
We need to investigate the database solution for our project. We should use a database that is cross-platform oriented, requires no installation, is distributed, and uses a socket.

The most database solution that works with node.js is implemented as a back-end that operates separately and provides a driver that can bind in node.js.

The following database solutions were investigated.
- Noms : This is the most ideal database, but it does not support the window environment. (There is no plan in the future.)
- MongoDB : Express is the most used database, but window needs to be installed.
- Levelup : No need to install, but access to file directly without using socket.
- Cassandra : By default, it does not support window environment. If you use DataSax, you can use it on Windows. But window needs to be installed.

In addition, express and frequently used solutions are as follows.
- Couchbase
- CouchDB
- MySQL
- Neo4j
- PostgreSQL
- Redis
- SQL Server
- SQLite
- ElasticSearch

**Comment by hyungheo** [comment]
Investing noms is very worth to develop this project.

**Comment by romandev** [comment]
I agree with @hyungheo's comment. But how can we apply it in our project?
The Noms doesn't support Windows platform for now.
Do you have a plan to try to build it for Windows platform?
If so, I don't disagree with it but we should probably introduce automatic build system periodically.

**Comment by CoconutPerm** [comment]
There are two ways.

1. Find out how to make Mongo DB binary.
2. Use Redis.
