### ISSUE TITLE
[Travis] Check coding style for Airbnb

### ISSUE THREAD

**Issue by Wuseok** [romandev/absolute#38]
@romandev requested.
Let's try to check codring style like Airbnb.
we'll discuss this issue with @gogag1 and start to solve this issue.

**Comment by nadongguri** [comment]
I'm already in.

**Comment by romandev** [comment]
I'll assign @nadongguri, @Wuseok and @gogag1 on this issue.

**Comment by romandev** [comment]
Thank you for raising on this issue @Wuseok 👍

**Comment by romandev** [comment]
https://github.com/romandev/absolute/pull/80
