### ISSUE TITLE
Should implement posix.sh for Linux/Mac.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#4]
Introduced run.cmd script to isolate Windows and POSIX in decf6c5

From now, we should finish to implement posix.sh to support Linux and Mac platform.
The script should be written as per [bash scripting guide.](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/Bash-Beginners-Guide.html)

Note that the script need to distinguish Linux x86, Linux x64, and Darwin by default.

**Comment by nadongguri** [comment]
reference about POSIX : https://en.m.wikipedia.org/wiki/POSIX#POSIX-oriented_operating_systems

simply saying, linux is unix-like system and not POSIX-certified but mostly POSIX-compliant. :-)

**Comment by romandev** [comment]
@nadongguri Thank you for the information.

**Comment by romandev** [comment]
https://github.com/romandev/absolute/commit/975f3c938cae9b357e0ec44ad3c9b1eee9183966
