### ISSUE TITLE
Image File uploading to server

### ISSUE THREAD

**Issue by Wuseok** [romandev/absolute#46]
File upload library: multer 
- it is express middleware.
- it support to sending multipart/form-data format.

File resizing library: graphicsmagick
- it support to make thumbnail, image resizing, blur, etc

Here it is sample source code.
http://webframeworks.kr/tutorials/expressjs/expressjs_file_upload/

server architecture
http://engineering.vcnc.co.kr/2016/05/ondemand-image-resizing/

**Comment by romandev** [comment]
Or we can save the data as data url(base64 encoded) to database. :)

**Comment by Wuseok** [comment]
I checked to save Base64 encoded image file in database.
It normally not used this flow.
Because Base64 encoding increases the storage requirement by 33% over a raw binary format. It also increases the amount of data that must be read from persistent storage, which is still generally the largest bottleneck in computing. It's generally faster to read less bytes and encode them on the fly. 

in case of 600KB under image size, it is faster than file transfer. but our scenario, usually 3~4MB or bigger image file will be transferred.
I think it is inefficient. How about your opinion? @romandev
