### ISSUE TITLE
We need to check downloading file integrity.

### ISSUE THREAD

**Issue by gogag1** [romandev/absolute#66]
We are checking nodejs  and mongodb directory.
If there is no folder, we will download each one.

But if it failed when we are downloading, we get directory, but file is not enough to run.
So we need to check downloading file integrity.

Below log is when downloading failed.
KOs-iMac:absolute kobyoungkwon$ ./run.cmd 
./scripts/run: line 25: platform: command not found
./scripts/run: line 14: platform: command not found
./scripts/run: line 18: /Users/kobyoungkwon/romandev/absolute/platform/nodejs/bin/npm: No such file or directory
./scripts/run: line 19: /Users/kobyoungkwon/romandev/absolute/platform/nodejs/bin/npm: No such file or directory

**Comment by coconutperm** [comment]
We need platform version checking also.

**Comment by romandev** [comment]
This issue is about legacy codes.
