### ISSUE TITLE
Javascript coding style guide.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#7]
Currently, there is no public style guide in our project.
We just mentioned following the Google coding style guide but is it a best way?

Here are some coding style guide examples (including translated version):
* Google: https://google.github.io/styleguide/jsguide.html
* AirBnB: https://github.com/tipjs/javascript-style-guide
* Idiomatic.js: https://github.com/rwaldron/idiomatic.js/

**Comment by nadongguri** [comment]
https://github.com/feross/standard 
it is automated coding convention check tool.

**Comment by romandev** [comment]
Who is able to follow this issue up?
As I remember, we already decided to follow airbnb style guide in our project.
Therefore, we should introduce lint-tool for the style.
@nadongguri, @gogag1, @Wuseok

**Comment by romandev** [comment]
We are using airbnb coding style with lint.
We can use 'absolute lint' command since https://github.com/romandev/absolute/pull/80.
