### ISSUE TITLE
Nodemon is not working when it run with forever.

### ISSUE THREAD

**Issue by coconutperm** [romandev/absolute#71]
forever's child process cannot find nodemon package.
I guess this problem is spawn's path issue by --prefix option of npm.

======================================
* Error logs.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by coconutperm** [comment]
* Identified : Child process cannot use path of script, can use global path only.

**Comment by coconutperm** [comment]
* Identified : Child process use only pull file name like 'nodemon.cmd'.

So I report to 'forever' module repo. and i will find workaround for our project.
https://github.com/foreverjs/forever-monitor/issues/140

**Comment by coconutperm** [comment]
I found new solution.

http://pm2.keymetrics.io/

**Comment by coconutperm** [comment]
http://www.tutorialbook.co.kr/entry/PM2-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-NodeJS-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0

**Comment by Jishaxe** [comment]
This is caused by https://github.com/nodejs/node-v0.x-archive/issues/2318
As a workaround, add `spawnWith: {shell: true}` to your config.
