### ISSUE TITLE
Mongo db file path issue

### ISSUE THREAD

**Issue by coconutperm** [romandev/absolute#72]
We use mongodb database solution for our project.
And we should define options for mongodb like logPath and dbPath.. and so on.

So, We need talk about path and make config file.

We have three issues.

1. where is dbPath?
2. where is logPath?
3. what is better between 2 case. 
   1) 'make config file and commit to absolute repo'
   2) 'make config file when run script.' <-- I expect.

let's talk about this!

**Comment by romandev** [comment]
+1 but is there no existing configuration file in mongo db?

**Comment by coconutperm** [comment]
no existing configuration in mongo db. it`s local configuration.

**Comment by romandev** [comment]
1. dbPath= ./database
2. logPath= ./log
3. 'make config file and commit to absolute repo'

**Comment by coconutperm** [comment]
Run all of the following commands in Command Prompt with “Administrative Privileges”.
mongod.exe --config "C:\Program Files\MongoDB\Server\3.4\mongod.cfg" --install

**Comment by coconutperm** [comment]
sc.exe create MongoDB binPath= "\"C:\Program Files\MongoDB\Server\3.4\bin\mongod.exe\" --service --config=\"C:\Program Files\MongoDB\Server\3.4\mongod.cfg\"" DisplayName= "MongoDB" start= "auto"

**Comment by coconutperm** [comment]
Refer below link:
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#install-and-run-the-mongodb-service

**Comment by coconutperm** [comment]
Configuration Link:
https://docs.mongodb.com/manual/reference/configuration-options/

**Comment by coconutperm** [comment]
* Problem :
 1. 2017-02-20T17:24:51.207+0900 F CONTROL  [main] Failed global initialization: BadValue: dbPath requires an absolute file path with Windows services
 2. 2017-02-20T17:26:57.365+0900 I CONTROL  [main] Error connecting to the Service Control Manager: 액세스가 거부되었습니다. (5)

**Comment by coconutperm** [comment]
* Config file
systemLog:
    destination: file
    path: ../../../log/mongod.log
storage:
    dbPath: c:/Workspace/git/absolute/database
processManagement:
   windowsService:
      serviceName: AbsoluteDB
      displayName: AbsoluteDB
      description: AbsoluteDB

**Comment by coconutperm** [comment]
https://github.com/christkv/node-mongodb-native
