### ISSUE TITLE
Test automation

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#8]
To write safer code, we should consider to introduce test automation ways.
* How can we test platform dependent codes?
  * Do we need test servers?
* How can we test server side codes?
  * There might be Node JS modules for unit test.
* How can we test client side codes?
  * Do we need to consider cross-browsing?

**Comment by Wuseok** [comment]
@romandev @gogag1 
I have a question about test automation tool.
Is it E2E(End-to-End) test tool? or only server side source codes test tool?

px) here I found to explained E2E test tool and nightwatch.js tool
http://blog.coderifleman.com/2016/06/17/e2e-test-and-nightwatch/

**Comment by romandev** [comment]
@Wuseok @gogag1 
It will be better to cover as many tests as possible.
But right now, it's urgent to introduce CI tool instead of E2E tool.
For example, we can consider to introduce travis CI tool.
As I know, there will be many information on the internet to integrate the tool with github.

**Comment by romandev** [comment]
* Here are some links:
  * https://blog.outsider.ne.kr/781
  * http://nnoco.tistory.com/227

**Comment by Wuseok** [comment]
Thank you @romandev 
We'll prepare to introduce test automation tool and CI tool.

**Comment by romandev** [comment]
You guys, could you please update this issue?
I'd like to apply 'Travis' to our project.
I think the first target can be lint-test tool.
For example, if someone uploads a patch(pull request), the lint test will run.
Then, if the codes are satisfied according to our coding style guide(airbnb style), the test will be passed. Otherwise, will be failed.

**Comment by Wuseok** [comment]
Thank you @romandev 
I added new issue about your suggestion.

**Comment by romandev** [comment]
We already introduced Travis for CI. (But we should still support Windows platform)
