### ISSUE TITLE
[Hackathon] Implement deep link to open an external browser.

### ISSUE THREAD

**Issue by romandev** [romandev/absolute#96]
When sending the message via KakaoTalk, the link will be opened on internal WebView.
Then, we can not control service worker and related features.
So, we have to implement and use deep link to open the url to an external browser.

**Comment by gogag1** [comment]
![deep link](https://cloud.githubusercontent.com/assets/3260994/23413143/2bfc96da-fe1b-11e6-884f-40fce441e2f1.png)
